In [3]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x, y

(tensor(3.), tensor(2.))

In [4]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [6]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

In [8]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [16]:
B = A.T
print(A)
print(B)
torch.mm(A, B)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


tensor([[  14,   38,   62,   86,  110],
        [  38,  126,  214,  302,  390],
        [  62,  214,  366,  518,  670],
        [  86,  302,  518,  734,  950],
        [ 110,  390,  670,  950, 1230]])

In [19]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [20]:
torch.abs(u).sum()

tensor(7.)

In [21]:
torch.norm(torch.ones(4, 9))

tensor(6.)